### ISSUE TITLE
Proposal for V1 spec layout

### ISSUE THREAD

**Issue by j-griffith** [NetApp/cake#74]
We need to settle in on a layout for our spec yaml.  Yes, we have one that we've been using, but we need to put in some thought toward extendability and cleaning things up.  It would also be nice to have one spec file example, and just use sections based on different providers and engines.

Here's a first pass at what I was thinking, would like to get input and flush this out, then we can implement it and fix up genconfig.

`
# cake spec file proposal
ProviderType: "vsphere"
EngineType: "rke"
VsphereProviderConfig:
  URL: "https://xxxxx"
  Username: "user"
  Password: "pass"
  Datacenter: "my-dc"
  ResourcePool: ""
  DataStore: "my-ds"
  ManagementNetwork: "my-mgmt-net"
  StorageNetwork: "my-stg-net"
  Folder: "my-folder"
  OVA:
    NodeTemnplate: "http://.../.../"
CloudInit:
  SSH:
    Username: "user"
    KeyPath: "Not sure what/why we have this?"
    AuthorizedKeys:
      - "your ssh-pub keys you wanted injected in to the machine here"
Cluster:
  NumWorkerNodes: 2
  NumControlNodes: 1
  NodeStaticIPs: # If empty use DHCP
    - "10.10.10.10"
    - "10.10.10.11"
    - "10.10.10.12"
  LBStaticIPs:
    - "xxxx"
    - "xxxx"
  Nodes: #optional section to specify nodes individually (overrides and duplicate info from automated section above
    - name: "node-1" #optional, auto-generated from cluster name if omitted
      IP: "10.10.10.10" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
      role: "master"
    - name: "node-2" #optional, auto-generated from cluster name if omitted
      IP: "10.10.10.11" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
      role: "worker"
    - name: "node-3" #optional, auto-generated from cluster name if omitted
      IP: "10.10.10.12" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
      role: "worker"

RKEConfig:
  RKEConfigPath: "/rke-config.yaml"
RancherConfig:
  RancherHostname: "my.rancher.org"
  Users:
    - Username:
      AuthMethod:
    - Username:
      AuthMethod:
`

**Comment by hulquest** [comment]
I like this.

In the absence of NodeStaticIPs, then DHCP is assumed?  Or do I need to have a NodeStaticIPs with an empty value?  I like the former but I realize there is an argument to infer behavior based on empty values.  Just trying to reduce "optional/optional" chains or situations where we have to defend "well, that kvp is only applicable when SomeOtherKey is active"

Another way would be to have an IPAddress section and types for everything we support.  It's an easy-ish way to plug in new schemes or applications.  This is probably easier to code and test since only the selected section values will be used.

There.  I've come full-circle on supporting empty blocks, to omitting them and back to supporting them.  I'll put some more thought into an IPAddress section and toss it out for comments.

**Comment by j-griffith** [comment]
> In the absence of NodeStaticIPs, then DHCP is assumed? Or do I need to have a NodeStaticIPs with an empty value?

Correct, if omitted we assume DHCP.  It's the opposite of your dependency chain example though, there's a default and it's DHCP, you can override that if you wish.

> Another way would be to have an IPAddress section and types for everything we support. It's an easy-ish way to plug in new schemes or applications. This is probably easier to code and test since only the selected section values will be used.

Yeah, that's a reasonable approach as well, so you're thinking something like:

```
///
IPConfig:
  UseDHCP: False
  IPs:
    - 9.9.9.9
    - 9.9.9.10
///
```

What I didn't like about something like that is it then introduces the need to do things like align number of IPs in the list with worker/master count provided etc.  So rather than mess with a bunch of stuff like that I went with the "default to DHCP approach, else include the Node info.  I do want to remove the ability to provide names in there though, it should probably look something like this:

```
  Nodes: #optional section to specify nodes individually (overrides and duplicate info from automated section above
    - role: worker-1
      IP: "10.10.10.10" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
      
    - role: worker-2
      IP: "10.10.10.11" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
      
    - role: master-1
      IP: "10.10.10.12" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
      
```

**Comment by hulquest** [comment]
> I do want to remove the ability to provide names in there though
Agree.  If anything, a name prefix or something that ends up with a predictable and queryable node names.

What about 
```yaml
Cluster:
   Name: accounting-app
...
```
Naming the cluster provides logical grouping with vSphere (folders) and would allow us to have common naming template.  Make a folder (inside cake) called accounting-app.  In it place the 3 nodes accounting-app-master-1, accounting-app-worker-1 and accounting-app-worker-2

**Comment by hulquest** [comment]
@j-griffith what are examples of AuthMethod?  Basic has to be one but what else?

**Comment by j-griffith** [comment]
Yeah, we have ClusterName, I just missed it in that example.  As far as AuthMethod, that's up to you :). That could be something like sucking over your vsphere users, implementing some sort of ldap or whatever I don't know.  Just reserving the ability.

**Comment by jacobweinstock** [comment]
I like where we're heading.

For things like auth in the rancher engine config, I'm more in favor of holding off on adding these until we have accepted a proposal and understand their use.  Then when we're closer to them being prioritized and implemented we add them in. Things can change. Lets just be a little more sure.

I like the node section for overriding worker and control node defaults and for allowing static IPs or for DHCP host reservations.

To push forward a little more:

```yaml
# cake spec file proposal
ProviderType: "vsphere"
EngineType: "rke"
ClusterName: "random"
Providers:
  Vsphere:
    URL: "https://xxxxx"
    Username: "user"
    Password: "pass"
    Datacenter: "my-dc"
    ResourcePool: "my-rp"
    DataStore: "my-ds"
    ManagementNetwork: "my-mgmt-net"
    StorageNetwork: "my-stg-net"
    Folder: "my-folder"
    OVA:
      NodeTemnplate: "http://.../.../"
  KVM:
    URL: ""
    Username: ""
    Password: ""
Engines:
  Rancher:
    ConfigPath: "/rke-config.yaml"
    Hostname: "my.rancher.org"
    KeyPath: "quark of rancher engine"
    Users:
      - Username:
        AuthMethod:
      - Username:
        AuthMethod:
  Capv:
    GithubToken: ""
CloudInit:
  SSH:
    Username: "user"
    AuthorizedKeys:
      - "your ssh-pub keys you wanted injected in to the machine here"
Cluster:
  KubernetesVersion: "v1.17.4-rancher1-3"
  KubernetesPodCidr: "10.217.0.0/16"
  KubernetesServiceCidr: "10.96.0.0/12"
  WorkerNodeCount: 2
  ControlNodeCount: 1
  LoadBalancerIPs:
    - "10.5.5.5"
    - "10.5.5.6"
  Nodes: #optional section to specify nodes individually (overrides and duplicate info from automated section above
    - Role: "controlplane"
      IP: "10.10.10.10" #optional, DHCP if omitted
      MAC: "30:23:03:73:a5:a7" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
    - Role: "worker"
      IP: "10.10.10.11" #optional, DHCP if omitted
      MAC: "30:23:03:73:a5:a8" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
    - Role: "worker"
      IP: "10.10.10.12" #optional, DHCP if omitted
      MAC: "30:23:03:73:a5:a9" #optional, DHCP if omitted
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
```

**Comment by hulquest** [comment]
I'll toss out a version that trades overrides for simplicity.  Also, I left the (YUGE!) CIDR ranges since I'm not sure if the management cluster would need them. 

The notable changes:
* node template per role.  Do worker (or control) nodes need to be different from each other? 
* added a section for proxy configuration.  We'll need this sooner rather than later.
* added a static network configuration section.   
* remove lb section.  Do management clusters need load balancing?  
* change engine type to rancher so it matches the rancher engine section.

```yaml
# cake spec file proposal
ProviderType: "vsphere"
EngineType: "rancher"
ClusterName: "random"
Providers:
  Vsphere:
    URL: "https://xxxxx"
    Username: "user"
    Password: "pass"
    Datacenter: "my-dc"
    ResourcePool: "my-rp"
    DataStore: "my-ds"
    ManagementNetwork: "my-mgmt-net"
    StorageNetwork: "my-stg-net"
    Folder: "my-folder"
    OVA:
      NodeTemnplate: "http://.../.../"
  KVM:
    URL: ""
    Username: ""
    Password: ""
Engines:
  Rancher:
    ConfigPath: "/rke-config.yaml"
    Hostname: "my.rancher.org"
    KeyPath: "quark of rancher engine"
    Users:
      - Username:
        AuthMethod:
      - Username:
        AuthMethod:
  Capv:
    GithubToken: ""
CloudInit:
  SSH:
    Username: "user"
    AuthorizedKeys:
      - "your ssh-pub keys you wanted injected in to the machine here"
  CustomScript:
    - "/path/to/local/custom/script"
Cluster:
  Version: "v1.17.4-rancher1-3"
  # PodCidr: "10.217.0.0/16"
  # ServiceCidr: "10.96.0.0/12"
  WorkerNodeCount: 2
  ControlNodeCount: 1
  NetworkInfo: 
    - IPAddresses:
        Provider: "DHCP" # or "Static"
        StaticConfiguration:  # validate: length of this list == sum(WorkerNodeCount+ControlNodeCount)
            - "x.x.x.x"  # control nodes first, then workers then LB
            - "x.x.x.x"  # worker address in this 1x2 example
            - "x.x.x.x"  # worker
    - Domain: "your.company.com"
      Gateway: "x.x.x.x"
      SubnetMask: "255.255.255.0"
      Nameservers:
        - "x.x.x.x"
        - "x.x.x.x"
    - Proxy:
        Host: ""
        Port: ""
        User: ""
        Password: ""
  NodeTemplates: 
    - Role: "control"
      CPUCount: 2
      Disk: "10G"
      Memory: "4G"
    - Role: "worker"
      CPUCount: 2
      Disk: "15G"
      Memory: "8G"

**Comment by jacobweinstock** [comment]
Hey @hulquest , the podcidr and servicecidr are definitely needed. the management cluster is still a kubernetes cluster. For your spec proposal, how would i add an additional network interface to all the worker nodes? if i wanted to have prometheus running in the management cluster with persistent storage i might want to use trident and might need to access storage through a different network.

**Comment by hulquest** [comment]
I guess I view the management cluster as more of a black box for the consumer of it.  I like the  use case you raise and I would treat that as incremental value add beyond a 1.0/initial release. How do you view the management cluster?

**Comment by jacobweinstock** [comment]
There's no expectation that cake provides a black box management cluster.  Management cluster operations, life cycle management is a [non-goal](https://github.com/NetApp/cake#non-goals) of cake.

I'm not saying we need additional network interfaces now. I'm just not seeing how the `NetworkInfo` section in your proposed spec would be able to accommodate additional network interfaces, even in the future.

**Comment by bgentry-ntap** [comment]
I'm in favor of the 'Nodes' section including the VM and network info instead of separate blocks. Also the KeyPath happens to be used by rancher, but any engine that needs one node to communicate with other nodes will need a private key there to ssh to the other nodes.

**Comment by jacobweinstock** [comment]
maybe we need to break this spec down and get agreement on parts instead of the whole thing at once. Lets look at everything but the `Cluster` section and see. Any comment, suggestions, etc on this part of the spec?

```yaml
# cake spec file proposal
ProviderType: "vsphere"
EngineType: "rancher"
ClusterName: "random"
Providers:
  Vsphere:
    URL: "https://xxxxx"
    Username: "user"
    Password: "pass"
    Datacenter: "my-dc"
    ResourcePool: "my-rp"
    DataStore: "my-ds"
    ManagementNetwork: "my-mgmt-net"
    StorageNetwork: "my-stg-net"
    Folder: "my-folder"
    OVA:
      NodeTemnplate: "http://.../.../"
  KVM: ## will be removed as there's no kvm provider implemented
    URL: ""
    Username: ""
    Password: ""
Engines:
  Rancher:
    ConfigPath: "/rke-config.yaml"
    Hostname: "my.rancher.org"
    KeyPath: "quark of rancher engine"
    Users: ## maybe removed until we understand this use-case better
      - Username:
        AuthMethod:
      - Username:
        AuthMethod:
  Capv:
    GithubToken: ""
CloudInit:
  SSH:
    Username: "user"
    AuthorizedKeys:
      - "your ssh-pub keys you wanted injected in to the machine here"
  CustomScript: ## will need to be implemented
    - "/path/to/local/custom/script"
```

**Comment by bgentry-ntap** [comment]
@jacobweinstock good idea. KeyPath should still be part of SSH IMO. I agree users should be removed until implemented, same with all unimplemented fields I think it will be easier to keep track of what works (or should) and what doesn't

**Comment by j-griffith** [comment]
> @jacobweinstock good idea. KeyPath should still be part of SSH IMO. I agree users should be removed until implemented, same with all unimplemented fields I think it will be easier to keep track of what works (or should) and what doesn't

To be clear, I added some of the unused/non-existant fields simply to illustrate a way to extend things in the future if/as needed.  I had no intention of implementing anything that doesn't exist but I don't want to see another refactor of everything again if we can avoid it.

**Comment by jacobweinstock** [comment]
ok, lets get some votes on this:

```yaml
# cake spec file proposal
ProviderType: "vsphere"
EngineType: "rancher"
ClusterName: "random"
Providers:
  Vsphere:
    URL: "https://xxxxx"
    Username: "user"
    Password: "pass"
    Datacenter: "my-dc"
    ResourcePool: "my-rp"
    DataStore: "my-ds"
    ManagementNetwork: "my-mgmt-net"
    StorageNetwork: "my-stg-net"
    Folder: "my-folder"
    OVA:
      NodeTemnplate: "http://.../.../"
      BootstrapTemplate: "http://..."
      LoadbalancerTemplate: "http://..."
Engines:
  Rancher:
    ConfigPath: "/rke-config.yaml"
    Hostname: "my.rancher.org"
  Capv:
    GithubToken: ""
CloudInit:
  SSH:
    Username: "user"
    KeyPath: "location/to/put/this/one/a/bootstrapper/id_rsa"
    AuthorizedKeys:
      - "your ssh-pub keys you wanted injected in to the machine here"
```

**Comment by j-griffith** [comment]
I'm pretty happy with the last proposal from @jacobweinstock https://github.com/NetApp/cake/issues/74#issuecomment-629462582

It still needs *something* along the equivalent of a `Cluster, Topology or Nodes` section for things like Node sizing, count and possibly IP addresses.

**Comment by jacobweinstock** [comment]
Ben and i discussed offline and we came up with this below. let me know your feedback @hulquest, @j-griffith  

```yaml
# cake spec file proposal
ClusterName: "random"
Providers:
  Type: "vsphere"
  Vsphere:
    URL: "https://xxxxx"
    Username: "user"
    Password: "pass"
    Datacenter: "my-dc"
    ResourcePool: "my-rp"
    DataStore: "my-ds"
    Networks:
      Management: "my-mgmt-net"
      Storage: "my-stg-net"
    Folder: "my-folder"
    OVA:
      NodeTemnplate: "http://.../.../"
      BootstrapTemplate: "http://..."
      LoadbalancerTemplate: "http://..."
Engines:
  Type: "rancher"
  Rancher:
    ConfigPath: "/rke-config.yaml"
    Hostname: "my.rancher.org"
  Capv:
    GithubToken: ""
CloudInit:
  SSH:
    Username: "user"
    KeyPath: "location/to/put/this/one/a/bootstrapper/id_rsa"
    AuthorizedKeys:
      - "your ssh-pub keys you wanted injected in to the machine here"
Cluster:
  Version: "v1.17.4"
  PodCidr: "10.217.0.0/16"
  ServiceCidr: "10.96.0.0/12"
  LoadBalancerIPs: ## leave for now, need more info about different load balancer we might use and if this is the right naming, etc
    - "10.5.5.5"
    - "10.5.5.6"
  Networks:
    Management: # optional section for when using static IPs, these are used only if a node below has an IP
      - Domain: "your.company.com"
        Gateway: "x.x.x.x"
        SubnetMask: "255.255.255.0"
        Nameservers:
          - "x.x.x.x"
          - "x.x.x.x"
  Nodes:
    - Role: "controlplane"
      Network:
        Interface1:
          IP: "10.10.10.10" #optional, DHCP if omitted
          Network: "Management"
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
    - Role: "worker"
      Network:
        Interface1:
          IP: "10.10.10.11" #optional, DHCP if omitted
          Network: "Management"
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
    - Role: "worker"
      Network:
        Interface1:
          IP: "10.10.10.12" #optional, DHCP if omitted
          Network: "Management"
      CPUCount: 2
      Disk: "50G"
      Memory: "8G"
```
